### PR TITLE
#3

### PR DESCRIPTION
**Pull request by FedericoCarli**
Added inclusion.stages. I did not implement print.inclusion.stages.sevt because the function is already a kind of print, in the way it is already implemented.

mod1 <- stndnaming.sevt(bhc.sevt(full(PhDArticles, lambda = 1)))
mod2 <- stndnaming.sevt(fbhc.sevt(full(PhDArticles, lambda = 1)))
comparison <- inclusion.stages(mod1, mod2)
print(comparison)

### CODE REVIEW

**Comment by gherardovarando** [comment]
@FedericoCarli build and check the package locally and then push also the document files, I think the Travis CI check are failing because there is no documentation for the `inclusion.stage` function

**Comment by gherardovarando** [comment]
@FedericoCarli does the `inclusion.stages` functions works properly also without `stndnaming.sevt` ?

**Comment by FedericoCarli** [comment]
Yes it works also without `stndnaming.sevt `. 
For the previous comment, how can I upload also document files? And what are these files?

**Comment by gherardovarando** [comment]
@FedericoCarli I will take care of it, no problem, thanks and nice work.

**Pull request merged**
